name: Test, Build & Push Docker image

# starts on push on main branch
on:
  push:
    branches: [ main ]

jobs:
  test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        # success() means if previous step was successfull (in this case its test)
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: success()
        run: docker build -t janjicdev/learn-docker:latest .

      - name: Push to Docker Hub
        if: success()
        run: docker push janjicdev/learn-docker:latest
          
      # example of auto deploy to azure (azure web app for containers)
      #- name: Deploy to Azure web app
      #  if: success()
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
      #    publish-profile: |
      #      {
      #        "publishingUserName": "${{ secrets.AZURE_USERNAME }}",
      #        "publishingPassword": "${{ secrets.AZURE_PASSWORD }}"
      #      }
      #    images: janjicdev/learn-docker:latest

      # step condition 3 options:
      # if: success() or failure() or always()
